apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo  # deployment 名称
  labels:  # deployment 的 labels
    app: nginx 
spec:
  replicas: 3  # 副本数量
  selector:    # 选择器，如何查找要管理的 pod
    matchLabels:
      app: deployment-demo-nginx
  template:
    metadata:
      labels:  # pod 的 labels
        app: deployment-demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
